services:
  - type: web
    name: calcella-calculator
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    startCommand: "npx serve . -l $PORT"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
